### ISSUE TITLE
AudioPIP Plugin is distributed without Permission of the Author!

### ISSUE THREAD

**Issue by gutemine** [fairbird/MyImagesFeeds-PY3#1]
You are distributing here my AudioPIP Plugin ipk WITHOUT permission, please remove IMMEDIATELY!

**Comment by fairbird** [comment]
Basically, this plugin does not work well with open source images or with Python 3, and I really wanted to delete it and forgot.... I have deleted it now...
https://github.com/fairbird/MyImagesFeeds-PY3/commit/21d4bf552094ecd15349e79bedcf399c9a8c8ff0
